test/snapshot (#15)
* fix: output err to stderr

* test: add snapshot tests

* test: use zsh

* test: install zsh

* test: add sudo

* test: remove upgrade

* fix: use POSIX awk (mawk) syntax

* test: remove unset varible

* ci: split steps

* test: update snapshots

---------

Co-authored-by: ras0q <ras0q@users.noreply.github.com>

diff --git a/cute b/cute
--- a/cute
+++ b/cute
@@ -8,7 +8,7 @@ _cute_usep="\037"
 _cute_find_markdown_files() {
   local max_depth=$1
   if [ -z "$max_depth" ]; then
-    echo "_cute_find_markdown_files: max_depth is required." > "/dev/stderr"
+    echo "_cute_find_markdown_files: max_depth is required." 1>&2
     return 1
   fi
 
@@ -28,12 +28,20 @@ _cute_extract_tasks() {
       gsub(/^-+|-+$/, "", str)
       return str
     }
-    match($0, /^```(sh|shell|bash|zsh)/, m) {
+    /^```(sh|shell|bash|zsh)$/ {
       if (shell_name != "") {
         print "_cute_extract_tasks: The previous codeblock is not closed." > "/dev/stderr";
         exit 1;
       }
-      shell_name = (m[1] == "shell" ? "sh" : m[1]);
+      if ($0 ~ /^```sh$/) {
+        shell_name = "sh";
+      } else if ($0 ~ /^```shell$/) {
+        shell_name = "sh";
+      } else if ($0 ~ /^```bash$/) {
+        shell_name = "bash";
+      } else if ($0 ~ /^```zsh$/) {
+        shell_name = "zsh";
+      }
       next
     }
     /^```/ {
@@ -64,8 +72,10 @@ _cute_extract_tasks() {
       command = command (command == "" ? "" : sep) $0 "\n";
       next
     }
-    match($0, /^#{1,6} (.+)/, m) {
-      task_name = m[1];
+    /^#{1,6} / {
+      line = $0;
+      sub(/^#+[[:space:]]+/, "", line);
+      task_name = line;
       next
     }
   '
@@ -250,7 +260,7 @@ cute() {
   for cute_task_identifier in "$@"; do
     local cute_task=$(_cute_find_task "$cute_tasks" "$cute_task_identifier")
     if [ -z "$cute_task" ]; then
-      echo "cute: Task not found: '$cute_task_identifier'"
+      echo "cute: Task not found: '$cute_task_identifier'" 1>&2
       return 1
     fi
 
@@ -261,7 +271,7 @@ cute() {
       cute_shell \
       cute_command
     if [ -z "$cute_task_name" ] || [ -z "$cute_task_slug" ] || [ -z "$cute_shell" ] || [ -z "$cute_command" ]; then
-      echo "cute: Failed to decode task: '$cute_task_identifier'"
+      echo "cute: Failed to decode task: '$cute_task_identifier'" 1>&2
       return 1
     fi
 
